Tb/xsx pipeline
PlayFab/UnrealMarketplacePlugin pull request #45
Opened 2021-03-18 20:02 UTC by toddbellMSFT

contains pipelines for Unreal to work on our GDK machine.

ALSO contains pipelines that haven't been checked in yet for vanilla Unreal on Windows.

2021-03-18 22:25 UTC, Vicodex approved these changes

2021-03-19 18:22 UTC, pgilmorepf requested changes
The biggest problem in my mind is that these files shouldn't be here. They should be here:
https://dev.azure.com/PlayFabInternal/Main/_git/UnrealGdkTemplate
This whole PR is private stuff that should not be customer visible, and you should move it to the template first, and then purge this PR branch, so that it's clean and even its history doesn't contain these files.

2021-03-19 18:22 UTC, pgilmorepf commented on UnrealGdkResourceTemplate.yml
> +  - bash: echo UnrealGdkResourceTemplate
I think now that we have a working pattern in place, we don't need these echo-debug jobs. The "cost" of this is pretty high (it has to instantiate an entire job just to print one line)

2021-03-19 18:22 UTC, pgilmorepf commented on UnrealGdkJobTemplate.yml
> +# JOB LEVEL TEMPLATE:
Template files should not be in this repo.
They should be here: https://dev.azure.com/PlayFabInternal/Main/_git/UnrealGdkTemplate

2021-03-19 18:22 UTC, pgilmorepf commented on UnrealGdkStepTemplate.yml
> +    ./RunUAT.bat BuildCookRun -rocket -nop4 -project="$WORKSPACE/sdks/$SdkName/$ueVersion/ExampleProject/ExampleProject.uproject" -cook -stage -archive -archivedirectory="$archivePath" -package -clie
I like putting the meaty statements into a .sh file, as functions, and then the yml bash is just a series of function calls.
https://dev.azure.com/PlayFabInternal/Main/_git/UnityGdkTemplate?path=%2FunityGdk.sh

2021-03-19 18:23 UTC, pgilmorepf commented
After you move these files to the internal template location, I'll review more deeply.

2021-03-19 18:23 UTC, closed without merging