Update PlayFabAuthenticationContext.h.ejs
PlayFab/UnrealMarketplacePlugin pull request #57
Opened 2022-03-24 20:05 UTC by toddbellMSFT

removing ClientAdminSecurityCheck. Devs have been complaining they need this for local test builds. This was intended to prevent shipping a sever security issue, but it has been determined this is more of a hinderance to the development cycle, and devs should already understand admin function calls shouldn't be built into release.

2022-03-24 21:01 UTC, amccalib requested changes

2022-03-24 21:01 UTC, amccalib commented on template/source/PlayFab/Source/PlayFabCommon/Public/PlayFabAuthenticationContext.h.ejs
> -        checkf(
I'm fine with this, but you might also want to check with someone like Andrew Martz to see if this is somewhere you could use an Ensure, instead (https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/ProgrammingWithCPP/Assertions/#:~:text=to%20the%20log.-,Ensure,-The%20Ensure%20family). That may be a way of achieving something similar in a non-blocking way.

2022-03-25 01:40 UTC, pgilmorepf approved these changes
Approved against my better judgement. :P

2022-03-25 19:11 UTC, amccalib approved these changes

2022-03-25 23:04 UTC, merged