Threading support for WriteTitleEvents
PlayFab/UnrealMarketplacePlugin pull request #9
Opened 2019-07-30 12:20 UTC by BenParburyMSFT

Support for Writing Title Events from a thread (providing you call SetTitleID on the API and provide an AuthenticationContext). Also support for DeveloperSecretKey access on AuthenticationContext by only providing one define.

2019-09-10 22:39 UTC, pgilmorepf approved these changes

2019-09-10 22:42 UTC, pgilmorepf commented
I've approved these changes, but they need to be migrated into our
https://github.com/PlayFab/SDKGenerator
repo before they'll actually be applied to the SDK and uploaded to the marketplace.

I'll leave the PR open until we internally do this (or until you submit the same PR to SdkGenerator).

2019-09-10 22:43 UTC, pgilmorepf requested changes
I've approved these changes, but they need to be migrated into our
https://github.com/PlayFab/SDKGenerator
repo before they'll actually be applied to the SDK and uploaded to the marketplace.

I'll leave the PR open until we internally do this (or until you submit the same PR to SdkGenerator).

I am flagging this as "Request Changes" so they're not accidentally committed here (which won't do anything), and as a reminder to the PlayFab team to address this soon.

2019-09-10 22:44 UTC, pgilmorepf commented
Thank you for your suggestions!

2019-09-17 00:51 UTC, toddbellMSFT commented
Some changes made it over. The specifics of routing around the PlayFabSettings should be fixed with the instancing of APIs.

2019-09-17 00:51 UTC, closed without merging